name: CI Tool Kit

on:
  pull_request:

jobs:
  citk:
    name: Code style and tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24"
      - name: Fetch main branch
        run: git fetch origin main:main
      - name: Install CITK tool
        run: |
          go install github.com/tjgurwara99/citk@latest
      - name: Run CITK tool
        run: |
          citk check -l go -b main
