name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  go_lint_and_test:
    name: Code lint and tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - name: Run gofmt check
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not formatted. Run 'gofmt -w .'"
            exit 1
          fi
      - name: Run Go Linter
        uses: golangci/golangci-lint-action@3c28b2cb75e1933038fca129074454e12a0f45d8
        with:
          version: latest
      - name: Run tests
        run: go test ./...
  codespell:
    name: Check for spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@71286cb40fe09b3222aff820311357b4e67cc206
        with:
          ignore_words_list: "actualy,nwe"
          skip: 'go.mod,go.sum'